### PR TITLE
added try/except for no content in note

### PR DESCRIPTION
**Pull request by jhellerstedt**
Hi,

Your script choked on my nsx file on subject-line-only notes, so I added a try/except where I assigned content to "no content" instead

Regards,

Jack

### CODE REVIEW

**Comment by Maboroshy** [comment]
Yep. Haven't tried it on an empty note. Thanks.

**Comment by Maboroshy** [comment]
Maybe the content of such notes should be empty, as it is in Note Station? What you think?

**Comment by jhellerstedt** [comment]
I just tried it again with "<div></div>" and it works on my nsx, I don't have any familiarity with pandoc.communicate, not sure how little can be passed into that line.

But in principle having it empty makes the most sense, I agree.

**Comment by Maboroshy** [comment]
I've modified your concept a little and pulled it up.

**Pull request merged**
